app = "musicfestival"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[deploy]
  # Use db:prepare so the first deploy can create the database automatically
  release_command = "/rails/bin/rails db:prepare"
